### ISSUE TITLE
chmod(): Nette\Utils\SafeStream::stream_metadata is not implemented

### ISSUE THREAD

**Issue by Ciki** [Gappa/WebLoader#3]
Hi, since https://github.com/Gappa/WebLoader/commit/fe9aa5bc9cee5efaac2fb55672c156a6f83f1527 generating files throws an error `chmod(): Nette\Utils\SafeStream::stream_metadata is not implemented!` as per https://github.com/nette/safe-stream/pull/5

for now it should be reverted I think. If you agree, please make a new release. Thanks!

**Comment by Ciki** [comment]
@Gappa what do you think?

**Comment by Ciki** [comment]
@Gappa Hi, just reminding this issue..

**Comment by Ciki** [comment]
Hi @Gappa would you please make a new release without that breaking change? Thanks

**Comment by Gappa** [comment]
Hi, sorry.

I haven't encountered this error so far. What is the use case? Generating & saving files works on my end.

**Comment by Ciki** [comment]
Hi, the use case is just regular usage, generating the files using `FileSystem::write` [here](https://github.com/Gappa/WebLoader/commit/fe9aa5bc9cee5efaac2fb55672c156a6f83f1527#diff-bdd0d64c8e43471e6d175998fe2ab7d5ebe6487844bbc6315348250361b71a4bR245)

When `nette.safe://` protocol is used the [chmod](https://github.com/nette/utils/blob/master/src/Utils/FileSystem.php#L145) fails

![chmod err](https://user-images.githubusercontent.com/342730/126339488-b811c113-1a15-4ade-8fff-7f24ed80d1dc.png)
