### ISSUE TITLE
Any PHP 8.2 compatible css minifer for WebLoader?

### ISSUE THREAD

**Issue by darkWolf-PR** [Gappa/WebLoader#5]
Hi - what is suggested css minifier for 6.x version? 

I have this config:

    scssFilter: App\Model\Webloader\ScssFilter
    cssMinFilter: Joseki\Webloader\CssMinFilter
    jsMinFilter: Joseki\Webloader\JsMinFilter

CSSmin keeps spamming this with PHP 8.2:

[2024-03-22 19-29-00] PHP Deprecated: Creation of dynamic property CssAtMediaStartToken::$MediaTypes is deprecated in /www/doc/www.domain.cz/www/vendor/natxet/cssmin/src/CssMin.php:4346

**Comment by Gappa** [comment]
Hi, 

this should still work:

- https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port

You can also try this:

- https://github.com/matthiasmullie/minify

However, you'll have to write the filter adapter for them.
